version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  groups:
    dependencies:
      applies-to: version-updates
      update-types:
      - "minor"
      - "patch"
      patterns:
      - "*"
  open-pull-requests-limit: 10
  ignore:
    # Playwright updates break the tests - TODO fix them!
    - dependency-name: "playwright*"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
  groups:
    gha:
      applies-to: version-updates
      patterns:
      - "*"
